version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs: # a collection of steps
  build:
    docker: # run the steps with Docker
      - image: circleci/openjdk:11.0.3-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
